// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:da0c516c-1467-4922-9854-1c04cfc5c5b8",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_npMLaTHr4",
    "aws_user_pools_web_client_id": "5901rb8f97d27pcqhkp1eob540",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://elice4go7fd2tc6cw2ynyivxei.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2gyv5pknsnarzcpyu3dzooaody",
    "aws_user_files_s3_bucket": "ng-chat2b22d66ae6a74f3aae487eb64ec680b0-test",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_content_delivery_bucket": "ng-chat-20191103202730-hostingbucket-test",
    "aws_content_delivery_bucket_region": "ap-northeast-1",
    "aws_content_delivery_url": "https://dsgd5mlb4bgbq.cloudfront.net"
};


export default awsmobile;
