// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-northeast-1",
  "aws_cognito_identity_pool_id": "ap-northeast-1:4b20cad8-be14-4478-bcee-f9d2d369841b",
  "aws_cognito_region": "ap-northeast-1",
  "aws_user_pools_id": "ap-northeast-1_tT7YppIn7",
  "aws_user_pools_web_client_id": "7ivrgcmergdtclgq2vmqdrkbve",
  "oauth": {},
  "aws_appsync_graphqlEndpoint": "https://asghxkpma5hovfsbjc3hefevo4.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-northeast-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_content_delivery_bucket": "ng-amplify-app-master",
  "aws_content_delivery_bucket_region": "ap-northeast-1",
  "aws_content_delivery_url": "https://d244atzvqtr2uv.cloudfront.net",
  "aws_user_files_s3_bucket": "ng-chatdecf4be0115149d588afaa9be2fe4341-master",
  "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
